// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htfyogsattqjyrzwmklm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0ZnlvZ3NhdHRxanlyendta2xtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjk1MTcsImV4cCI6MjA2Mzc0NTUxN30.kAXk4oLP9GBI5MFJyJ0TDpwR3NQyn8Hmj7Cu-MCt6-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);